[versions]
agp = "8.13.1"
kotlin = "2.2.21"
compose = "1.9.3"
activity = "1.12.0"
lifecycle = "2.9.6"
koin = "4.1.1"
kotlinx-collections = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
navigation = "2.9.1"
datastore = "1.2.0"
tink-android = "1.19.0"
ktor = "3.3.3"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
google-tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink-android" }


#KOIN
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin"}
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin"}
koin-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin"}
koin-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation", version.ref = "koin"}

#KOTLINX
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections" }

#KTOR
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-content = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

[bundles]
# This bundle has been used in convention feature plugin, don't remove it
koin = ["koin-compose", "koin-viewmodel", "koin-viewmodel-navigation"]
ktor = ["ktor-auth", "ktor-core", "ktor-content", "ktor-logging", "ktor-serialization"]
kotlinx = ["kotlinx-collections", "kotlinx-coroutines", "kotlinx-datetime"]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]
datastore = ["datastore", "datastore-preferences"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

#CONVENTION
androidApp = { id = "base.application", version = "unspecified" }
appCompose = { id = "base.compose", version = "unspecified" }
appLibrary = { id = "base.library", version = "unspecified" }
appFeature = { id = "base.feature", version = "unspecified" }