[versions]
agp = "8.13.0"
kotlin = "2.2.21"
compose = "1.9.2"
androidx-activity = "1.11.0"
androidx-lifecycle = "2.9.5"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

#CONVENTION
androidApp = { id = "base.application", version = "unspecified" }
appCompose = { id = "base.compose", version = "unspecified" }
appLibrary = { id = "base.library", version = "unspecified" }
appFeature = { id = "base.feature", version = "unspecified" }